
insert into CFG_ID_GENERATOR (TABLE_NAME, DOMAIN_ID, GENERATOR_TYPE, SEQUENCE_NAME, MAX_ID, START_VALUE, MIN_VALUE, MAX_VALUE, INCREMENT_VALUE, CYCLE_FLAG, CACHE_SIZE, SEQUENCE_CREATE_SCRIPT, HIS_TABLE_NAME, HIS_SEQUENCE_NAME, HIS_DATA_FLAG, HIS_MAX_ID, HIS_DONECODE_FLAG, STEP_BY, HIS_STEP_BY)
values ('VM_DEAL_TASK', 11, 'S', 'VM_DEAL_TASK$SEQ', 1, 1, 1, 999999999999, 1, 'N', 20, null, null, null, null, null, null, null, null);
insert into CFG_ID_GENERATOR (TABLE_NAME, DOMAIN_ID, GENERATOR_TYPE, SEQUENCE_NAME, MAX_ID, START_VALUE, MIN_VALUE, MAX_VALUE, INCREMENT_VALUE, CYCLE_FLAG, CACHE_SIZE, SEQUENCE_CREATE_SCRIPT, HIS_TABLE_NAME, HIS_SEQUENCE_NAME, HIS_DATA_FLAG, HIS_MAX_ID, HIS_DONECODE_FLAG, STEP_BY, HIS_STEP_BY)
values ('VM_EXCEPTION_RECORD', 11, 'S', 'VM_EXCEPTION_RECORD$SEQ', 1, 1, 1, 999999999999, 1, 'N', 20, null, null, null, null, null, null, null, null);
insert into CFG_ID_GENERATOR (TABLE_NAME, DOMAIN_ID, GENERATOR_TYPE, SEQUENCE_NAME, MAX_ID, START_VALUE, MIN_VALUE, MAX_VALUE, INCREMENT_VALUE, CYCLE_FLAG, CACHE_SIZE, SEQUENCE_CREATE_SCRIPT, HIS_TABLE_NAME, HIS_SEQUENCE_NAME, HIS_DATA_FLAG, HIS_MAX_ID, HIS_DONECODE_FLAG, STEP_BY, HIS_STEP_BY)
values ('VM_WF', 11, 'S', 'VM_WF$SEQ', 1, 1, 1, 999999999999, 1, 'N', 20, null, null, null, null, null, null, null, null);
insert into CFG_ID_GENERATOR (TABLE_NAME, DOMAIN_ID, GENERATOR_TYPE, SEQUENCE_NAME, MAX_ID, START_VALUE, MIN_VALUE, MAX_VALUE, INCREMENT_VALUE, CYCLE_FLAG, CACHE_SIZE, SEQUENCE_CREATE_SCRIPT, HIS_TABLE_NAME, HIS_SEQUENCE_NAME, HIS_DATA_FLAG, HIS_MAX_ID, HIS_DONECODE_FLAG, STEP_BY, HIS_STEP_BY)
values ('VM_TASK', 11, 'S', 'VM_TASK$SEQ', 1, 1, 1, 999999999999, 1, 'N', 20, null, null, null, null, null, null, null, null);
insert into CFG_ID_GENERATOR (TABLE_NAME, DOMAIN_ID, GENERATOR_TYPE, SEQUENCE_NAME, MAX_ID, START_VALUE, MIN_VALUE, MAX_VALUE, INCREMENT_VALUE, CYCLE_FLAG, CACHE_SIZE, SEQUENCE_CREATE_SCRIPT, HIS_TABLE_NAME, HIS_SEQUENCE_NAME, HIS_DATA_FLAG, HIS_MAX_ID, HIS_DONECODE_FLAG, STEP_BY, HIS_STEP_BY)
values ('VM_TASK_TS', 11, 'S', 'VM_TASK$SEQ', 1, 1, 1, 999999999999, 1, 'N', 20, null, null, null, null, null, null, null, null);
insert into CFG_ID_GENERATOR (TABLE_NAME, DOMAIN_ID, GENERATOR_TYPE, SEQUENCE_NAME, MAX_ID, START_VALUE, MIN_VALUE, MAX_VALUE, INCREMENT_VALUE, CYCLE_FLAG, CACHE_SIZE, SEQUENCE_CREATE_SCRIPT, HIS_TABLE_NAME, HIS_SEQUENCE_NAME, HIS_DATA_FLAG, HIS_MAX_ID, HIS_DONECODE_FLAG, STEP_BY, HIS_STEP_BY)
values ('VM_WF_ATTR', 11, 'S', 'VM_WF_ATTR$SEQ', 1, 1, 1, 999999999999, 1, 'N', 20, null, null, null, null, null, null, null, null);
insert into CFG_ID_GENERATOR (TABLE_NAME, DOMAIN_ID, GENERATOR_TYPE, SEQUENCE_NAME, MAX_ID, START_VALUE, MIN_VALUE, MAX_VALUE, INCREMENT_VALUE, CYCLE_FLAG, CACHE_SIZE, SEQUENCE_CREATE_SCRIPT, HIS_TABLE_NAME, HIS_SEQUENCE_NAME, HIS_DATA_FLAG, HIS_MAX_ID, HIS_DONECODE_FLAG, STEP_BY, HIS_STEP_BY)
values ('H_VM_TEMPLATE', 11, 'S', 'H_VM_TEMPLATE$SEQ', 1, 1, 1, 999999999999, 1, 'N', 20, null, null, null, null, null, null, null, null);
insert into CFG_ID_GENERATOR (TABLE_NAME, DOMAIN_ID, GENERATOR_TYPE, SEQUENCE_NAME, MAX_ID, START_VALUE, MIN_VALUE, MAX_VALUE, INCREMENT_VALUE, CYCLE_FLAG, CACHE_SIZE, SEQUENCE_CREATE_SCRIPT, HIS_TABLE_NAME, HIS_SEQUENCE_NAME, HIS_DATA_FLAG, HIS_MAX_ID, HIS_DONECODE_FLAG, STEP_BY, HIS_STEP_BY)
values ('VM_ALARM_CONFIG', 11, 'S', 'VM_ALARM_CONFIG$SEQ', 1, 1, 1, 999999999999, 1, 'N', 20, null, null, null, null, null, null, null, null);
insert into CFG_ID_GENERATOR (TABLE_NAME, DOMAIN_ID, GENERATOR_TYPE, SEQUENCE_NAME, MAX_ID, START_VALUE, MIN_VALUE, MAX_VALUE, INCREMENT_VALUE, CYCLE_FLAG, CACHE_SIZE, SEQUENCE_CREATE_SCRIPT, HIS_TABLE_NAME, HIS_SEQUENCE_NAME, HIS_DATA_FLAG, HIS_MAX_ID, HIS_DONECODE_FLAG, STEP_BY, HIS_STEP_BY)
values ('VM_ENGINE_TEMPLATE_VERSION', 11, 'S', 'VM_ENGINE_TEMPLATE_VERSION$SEQ', 1, 1, 1, 999999999999, 1, 'N', 20, null, null, null, null, null, null, null, null);
insert into CFG_ID_GENERATOR (TABLE_NAME, DOMAIN_ID, GENERATOR_TYPE, SEQUENCE_NAME, MAX_ID, START_VALUE, MIN_VALUE, MAX_VALUE, INCREMENT_VALUE, CYCLE_FLAG, CACHE_SIZE, SEQUENCE_CREATE_SCRIPT, HIS_TABLE_NAME, HIS_SEQUENCE_NAME, HIS_DATA_FLAG, HIS_MAX_ID, HIS_DONECODE_FLAG, STEP_BY, HIS_STEP_BY)
values ('VM_EXCEPTION_CODE', 11, 'S', 'VM_EXCEPTION_CODE$SEQ', 1, 1, 1, 999999999999, 1, 'N', 20, null, null, null, null, null, null, null, null);
insert into CFG_ID_GENERATOR (TABLE_NAME, DOMAIN_ID, GENERATOR_TYPE, SEQUENCE_NAME, MAX_ID, START_VALUE, MIN_VALUE, MAX_VALUE, INCREMENT_VALUE, CYCLE_FLAG, CACHE_SIZE, SEQUENCE_CREATE_SCRIPT, HIS_TABLE_NAME, HIS_SEQUENCE_NAME, HIS_DATA_FLAG, HIS_MAX_ID, HIS_DONECODE_FLAG, STEP_BY, HIS_STEP_BY)
values ('VM_EXCEPTION_RULE', 11, 'S', 'VM_EXCEPTION_RULE$SEQ', 1, 1, 1, 999999999999, 1, 'N', 20, null, null, null, null, null, null, null, null);
insert into CFG_ID_GENERATOR (TABLE_NAME, DOMAIN_ID, GENERATOR_TYPE, SEQUENCE_NAME, MAX_ID, START_VALUE, MIN_VALUE, MAX_VALUE, INCREMENT_VALUE, CYCLE_FLAG, CACHE_SIZE, SEQUENCE_CREATE_SCRIPT, HIS_TABLE_NAME, HIS_SEQUENCE_NAME, HIS_DATA_FLAG, HIS_MAX_ID, HIS_DONECODE_FLAG, STEP_BY, HIS_STEP_BY)
values ('VM_TEMPLATE_VERSION', 11, 'S', 'VM_TEMPLATE_VERSION$SEQ', 1, 1, 1, 999999999999, 1, 'N', 20, null, null, null, null, null, null, null, null);
insert into cfg_id_generator (TABLE_NAME, DOMAIN_ID, GENERATOR_TYPE, SEQUENCE_NAME, MAX_ID, START_VALUE, MIN_VALUE, MAX_VALUE, INCREMENT_VALUE, CYCLE_FLAG, CACHE_SIZE, SEQUENCE_CREATE_SCRIPT, HIS_TABLE_NAME, HIS_SEQUENCE_NAME, HIS_DATA_FLAG, HIS_MAX_ID, HIS_DONECODE_FLAG)
values ('VM_OBJECT_ITEM_KIND', 11, 'S', 'VM_OBJ_ITEM_KIND$SEQ', 1, 1, 1, 999999999999, 1, '', 20, '', '', '', '', null, '');
insert into cfg_id_generator (TABLE_NAME, DOMAIN_ID, GENERATOR_TYPE, SEQUENCE_NAME, MAX_ID, START_VALUE, MIN_VALUE, MAX_VALUE, INCREMENT_VALUE, CYCLE_FLAG, CACHE_SIZE, SEQUENCE_CREATE_SCRIPT, HIS_TABLE_NAME, HIS_SEQUENCE_NAME, HIS_DATA_FLAG, HIS_MAX_ID, HIS_DONECODE_FLAG)
values ('VM_OBJECT_ITEM_RELAT', 11, 'S', 'VM_OBJ_ITEM_RELAT$SEQ', 1, 1, 1, 999999999999, 1, '', 20, '', '', '', '', null, '');
insert into cfg_id_generator (TABLE_NAME, DOMAIN_ID, GENERATOR_TYPE, SEQUENCE_NAME, MAX_ID, START_VALUE, MIN_VALUE, MAX_VALUE, INCREMENT_VALUE, CYCLE_FLAG, CACHE_SIZE, SEQUENCE_CREATE_SCRIPT, HIS_TABLE_NAME, HIS_SEQUENCE_NAME, HIS_DATA_FLAG, HIS_MAX_ID, HIS_DONECODE_FLAG)
values ('VM_OBJECT_ITEM_KIND_ELEMENT', 11, 'S', 'VM_OBJ_ITEM_KIND_ELEMENT$SEQ', 1, 1, 1, 999999999999, 1, '', 20, '', '', '', '', null, '');
insert into cfg_id_generator (TABLE_NAME, DOMAIN_ID, GENERATOR_TYPE, SEQUENCE_NAME, MAX_ID, START_VALUE, MIN_VALUE, MAX_VALUE, INCREMENT_VALUE, CYCLE_FLAG, CACHE_SIZE, SEQUENCE_CREATE_SCRIPT, HIS_TABLE_NAME, HIS_SEQUENCE_NAME, HIS_DATA_FLAG, HIS_MAX_ID, HIS_DONECODE_FLAG)
values ('VM_OBJECT_ITEM', 11, 'S', 'VM_OBJ_ITEM$SEQ', 1, 1, 1, 999999999999, 1, '', 20, '', '', '', '', null, '');
insert into cfg_id_generator (TABLE_NAME, DOMAIN_ID, GENERATOR_TYPE, SEQUENCE_NAME, MAX_ID, START_VALUE, MIN_VALUE, MAX_VALUE, INCREMENT_VALUE, CYCLE_FLAG, CACHE_SIZE, SEQUENCE_CREATE_SCRIPT, HIS_TABLE_NAME, HIS_SEQUENCE_NAME, HIS_DATA_FLAG, HIS_MAX_ID, HIS_DONECODE_FLAG)
values ('VM_QUEUE_SERVER_REGIST', 11, 'S', 'VM_QUEUE_SERVER_REGIST$SEQ', 1, 1, 1, 999999999999, 1, '', 20, '', '', '', '', null, '');
commit;


