set global log_bin_trust_function_creators=1;

delimiter //
CREATE FUNCTION seq_nextval(seq_name char (60)) returns int
begin
 UPDATE SYS_SEQUENCES SET LAST_NUMBER= case last_number when 0 THEN last_insert_id(START_BY) else last_insert_id(LAST_NUMBER+INCREMENT_BY) end WHERE SEQUENCE_NAME=seq_name;
 RETURN last_insert_id();
end
//
delimiter ;

delimiter //
CREATE FUNCTION seq_curval(seq_name char (60)) returns int
begin
 DECLARE cur  int;
 select LAST_NUMBER into cur from SYS_SEQUENCES WHERE SEQUENCE_NAME=seq_name;
 RETURN  cur;
end
//
delimiter ;
 

CREATE TABLE `SYS_SEQUENCES` (
  `SEQUENCE_NAME` varchar(60) NOT NULL,
  `START_BY` BIGINT(20) UNSIGNED NOT NULL,
  `INCREMENT_BY` BIGINT(10) UNSIGNED NOT NULL,
  `LAST_NUMBER` BIGINT(20) UNSIGNED NOT NULL,
  PRIMARY KEY  (`SEQUENCE_NAME`)
) ENGINE=MyISAM ;



insert into SYS_SEQUENCES (`SEQUENCE_NAME`,`START_BY`,`INCREMENT_BY`,`LAST_NUMBER`)
values ('VM_DEAL_TASK$SEQ', 1, 1, 1);
insert into SYS_SEQUENCES (`SEQUENCE_NAME`,`START_BY`,`INCREMENT_BY`,`LAST_NUMBER`)
values ('VM_EXCEPTION_RECORD$SEQ', 1, 1, 1);
insert into SYS_SEQUENCES (`SEQUENCE_NAME`,`START_BY`,`INCREMENT_BY`,`LAST_NUMBER`)
values ('VM_WF$SEQ', 1, 1, 1);
insert into SYS_SEQUENCES (`SEQUENCE_NAME`,`START_BY`,`INCREMENT_BY`,`LAST_NUMBER`)
values ('VM_TASK$SEQ', 1, 1, 1);
insert into SYS_SEQUENCES (`SEQUENCE_NAME`,`START_BY`,`INCREMENT_BY`,`LAST_NUMBER`)
values ('VM_WF_ATTR$SEQ', 1, 1, 1);
insert into SYS_SEQUENCES (`SEQUENCE_NAME`,`START_BY`,`INCREMENT_BY`,`LAST_NUMBER`)
values ('H_VM_TEMPLATE$SEQ', 1, 1, 1);
insert into SYS_SEQUENCES (`SEQUENCE_NAME`,`START_BY`,`INCREMENT_BY`,`LAST_NUMBER`)
values ('VM_ALARM_CONFIG$SEQ', 1, 1, 1);
insert into SYS_SEQUENCES (`SEQUENCE_NAME`,`START_BY`,`INCREMENT_BY`,`LAST_NUMBER`)
values ('VM_ENGINE_TEMPLATE_VERSION$SEQ', 1, 1, 1);
insert into SYS_SEQUENCES (`SEQUENCE_NAME`,`START_BY`,`INCREMENT_BY`,`LAST_NUMBER`)
values ('VM_EXCEPTION_CODE$SEQ', 1, 1, 1);
insert into SYS_SEQUENCES (`SEQUENCE_NAME`,`START_BY`,`INCREMENT_BY`,`LAST_NUMBER`)
values ('VM_EXCEPTION_RULE$SEQ', 1, 1, 1);
insert into SYS_SEQUENCES (`SEQUENCE_NAME`,`START_BY`,`INCREMENT_BY`,`LAST_NUMBER`)
values ('VM_TEMPLATE_VERSION$SEQ', 1, 1, 1);
insert into SYS_SEQUENCES (`SEQUENCE_NAME`,`START_BY`,`INCREMENT_BY`,`LAST_NUMBER`)
values ('VM_QUEUE_SERVER_REGIST$SEQ', 1, 1, 1);
commit;

 

