-- CREATE TABLE
CREATE TABLE CFG_BO_MASK(
BO_NAME 							VARCHAR2(255) NOT NULL,
ATTR_NAME							VARCHAR2(255) NOT NULL,
MASK_FUNCTION_CLASS		VARCHAR2(255) NOT NULL,
STATE									CHAR(1)	NOT NULL,
REMARKS								VARCHAR2(255),
CONSTRAINT PK_CFG_BO_MASK PRIMARY KEY (BO_NAME,ATTR_NAME)
)
