-- Create table
create table GROUP_ACCOUNT
(
  GROUP_ACC_ID         NUMBER(11) not null,
  GROUP_ID             NUMBER(11) not null,
  ACC_ID               VARCHAR2(40) not null,
  ACC_ALIAS_NAME       VARCHAR2(100) not null,
  REC_STATUS           NUMBER(2) not null,
  DONE_DATE            DATE not null,
  VALID_DATE           DATE not null,
  EXPIRE_DATE          DATE not null,
  OP_ID                NUMBER(8) not null,
  ORG_ID               NUMBER(6) not null,
  DONE_CODE            NUMBER(12) not null,
  IS_SEND              NUMBER(2),
  CONTACT_PERSON       VARCHAR2(128),
  CONTACT_CARD_TYPE    NUMBER(2),
  CONTACT_CARD_CODE    VARCHAR2(20),
  CONTACT_BILL_ID      VARCHAR2(15),
  NEED_TO_SEND_MESSAGE NUMBER(2),
  CONTACT_NAME         VARCHAR2(128),
  ACC_BUSI_TYPE        NUMBER(5),
  NUM_EXT1             NUMBER(14),
  NUM_EXT2             NUMBER(14),
  VAR_EXT1             VARCHAR2(128),
  VAR_EXT2             VARCHAR2(128)
);
alter table GROUP_ACCOUNT
  add constraint PK_GROUP_ACCOUNT primary key (GROUP_ACC_ID)
  using index ;

-- Create table
create table GROUP_INFO
(
  GROUP_ID           NUMBER(11) not null,
  GRP_ID             NUMBER(11) not null,
  GROUP_NAME         VARCHAR2(200) not null,
  PASSWORD           VARCHAR2(30),
  GROUP_LEVEL        VARCHAR2(10) not null,
  GROUP_TYPE         VARCHAR2(10) not null,
  REGION_SPECIA      VARCHAR2(10) not null,
  GROUP_STATUS       NUMBER(2) not null,
  LEVEL_DEF_MODE     NUMBER(2) not null,
  REC_STATUS         NUMBER(2) not null,
  VOCATION           NUMBER(5) not null,
  VOCATION2          NUMBER(5) not null,
  VOCATION3          NUMBER(5) not null,
  GROUP_COUNTRY      NUMBER(8) not null,
  GROUP_PROVINCE     NUMBER(8) not null,
  GROUP_CITY         NUMBER(8) not null,
  REGION_TYPE        NUMBER(8) not null,
  REGION_DETAIL      NUMBER(8) not null,
  GROUP_ADDRESS      VARCHAR2(200) not null,
  GROUP_POSTCODE     NUMBER(6),
  POST_PROVINCE      NUMBER(8) not null,
  POST_CITY          NUMBER(8) not null,
  POST_ADDRESS       VARCHAR2(200),
  POST_POSTCODE      NUMBER(6),
  PHONE_ID           VARCHAR2(30) not null,
  FAX_ID             VARCHAR2(30),
  CARD_TYPE          NUMBER(2) not null,
  CARD_ID            VARCHAR2(40),
  OWNER_NAME         VARCHAR2(100),
  TAX_ID             VARCHAR2(40),
  NET_ADDRESS        VARCHAR2(80),
  PAY_TYPE           NUMBER(2),
  EMAIL              VARCHAR2(60),
  DEVELOP_TYPE       NUMBER(2) not null,
  PARTNER_ID         NUMBER(10),
  CREATE_DATE        DATE not null,
  DONE_DATE          DATE not null,
  VALID_DATE         DATE not null,
  EXPIRE_DATE        DATE not null,
  OP_ID              NUMBER(8) not null,
  ORG_ID             NUMBER(6) not null,
  DONE_CODE          NUMBER(12) not null,
  NOTES              VARCHAR2(200),
  CUSTOMER_ID        VARCHAR2(64),
  VPMN_ID            VARCHAR2(64),
  EXT_FIELD2         VARCHAR2(128),
  EXT_FIELD3         VARCHAR2(128),
  EXT_FIELD4         VARCHAR2(128),
  EXT_FIELD5         VARCHAR2(128),
  EXT_FIELD6         VARCHAR2(128),
  EXT_FIELD7         VARCHAR2(128),
  EXT_FIELD8         VARCHAR2(128),
  EXT_FIELD9         VARCHAR2(128),
  EXT_FIELD10        VARCHAR2(128),
  EXT_FIELD1         VARCHAR2(128),
  EXT_FIELD11        VARCHAR2(128),
  EXT_FIELD12        VARCHAR2(128),
  EXT_FIELD13        VARCHAR2(128),
  EXT_FIELD14        VARCHAR2(128),
  EXT_FIELD15        VARCHAR2(128),
  GROUP_COMPANY_TYPE NUMBER(2)
);
alter table GROUP_INFO
  add constraint PK_GROUP_INFO primary key (GROUP_ID)
  using index ;

-- Create table
create table GROUP_CONTRACT_INFO
(
  CONTRACT_ID    NUMBER(11) not null,
  CONTRACT_NAME           VARCHAR2(100) not null,
  CONTRACT_NO             VARCHAR2(50) not null,
  CONTRACT_TYPE           CHAR(1),
  GROUP_ID                NUMBER(11),
  FIRST_NAME              VARCHAR2(200),
  SECOND_NAME             VARCHAR2(200),
  THIRD_NAME              VARCHAR2(200),
  FIRST_DEPUTY_NAME       VARCHAR2(50),
  FIRST_DEPUTY_DUTY       VARCHAR2(50),
  FIRST_DEPUTY_LINKPHONE  VARCHAR2(50),
  FIRST_DEPUTY_TYPE       NUMBER(1),
  SECOND_DEPUTY_NAME      VARCHAR2(50),
  SECOND_DEPUTY_DUTY      VARCHAR2(50),
  SECOND_DEPUTY_LINKPHONE VARCHAR2(50),
  SECOND_DEPUTY_TYPE      NUMBER(1),
  THIRD_DEPUTY_NAME       VARCHAR2(50),
  THIRD_DEPUTY_DUTY       VARCHAR2(50),
  THIRD_DEPUTY_LINKPHONE  VARCHAR2(50),
  THIRD_DEPUTY_TYPE       NUMBER(1),
  SUBSCRIBE_DATE          DATE,
  SUBSCRIBE_PLACE         VARCHAR2(200),
  CONTRACT_VALID_DATE     DATE,
  CONTRACT_EXPIRE_DATE    DATE,
  CONTRACT_SOURCE         NUMBER(2),
  BUSI_DESC               VARCHAR2(256),
  DETAIL_FEE_DESC         VARCHAR2(256),
  OTHER_DESC              VARCHAR2(256),
  CONTRACT_PATH           VARCHAR2(100),
  CONTRACT_STATUS         NUMBER(2),
  REC_STATUS              NUMBER(2) not null,
  DONE_DATE               DATE not null,
  VALID_DATE              DATE not null,
  EXPIRE_DATE             DATE not null,
  OP_ID                   NUMBER(8) not null,
  ORG_ID                  NUMBER(6) not null,
  DONE_CODE               NUMBER(12) not null,
  MANAGER_ID              NUMBER(8)
);
alter table GROUP_CONTRACT_INFO
  add constraint PK_GROUP_CONTRACT_INFO primary key (CONTRACT_ID)
  using index ;

