-- Create table
create table CFG_SERVICE_CONTROL(
SERVER_NAME   VARCHAR(1000) NOT NULL,
SERVICE_NAME  VARCHAR(1000) NOT NULL,
METHOD_NAME   VARCHAR(1000),
LIMIT_COUNT 	BIGINT(6) NOT NULL,
STATE					CHAR(1)   NOT NULL,
REMARKS				VARCHAR(255)
);
