create table cfg_client_timeout
(
  SERVER_NAME  				VARCHAR(100) NOT NULL,
  INTERFACE_CLASSNAME	VARCHAR(300) NOT NULL,
  METHOD_NAME  				VARCHAR(100) NOT NULL,
  PARAMETER_COUNT  		BIGINT NOT NULL,
  TIMEOUT_SECOND  		BIGINT NOT NULL,
  STATE        				CHARACTER(1) NOT NULL,
  REMARKS      				VARCHAR(255),
  CONSTRAINT PK_CFG_CLIENT_TIMEOUT PRIMARY KEY (INTERFACE_CLASSNAME, METHOD_NAME, PARAMETER_COUNT)
);

